# fly.toml app configuration file generated for event-organizers-toolbox on 2023-10-24T00:05:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "event-organizers-toolbox"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
